name: Release Drafter

permissions:
  contents: write # 콘텐츠 읽기 및 쓰기 권한

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    needs: update-release-draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 현재 저장소의 릴리즈 목록 가져오기
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // Draft 릴리즈 검색
            const draftRelease = releases.data.find(release => release.draft);

            if (!draftRelease) {
              console.log("No draft release found.");
              return;
            }

            // Draft 릴리즈를 게시
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: draftRelease.id,
              draft: false, // Draft 상태 해제
            });

            console.log(`Published release: ${draftRelease.name}`);
