name: Release Drafter

on:
  push:
    branches:
      - main # 릴리즈 노트를 작성할 브랜치 (필요에 따라 변경 가능)
  pull_request:
    types: [closed] # PR이 머지될 때도 실행

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
