name: Release Drafter

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.15.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    needs: update-release-draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context } = require('@actions/github');

            const draftReleases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const latestDraft = draftReleases.data.find(release => release.draft);
            if (!latestDraft) {
              console.log("No draft release found.");
              return;
            }

            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: latestDraft.id,
              draft: false,
            });

            console.log(`Published release: ${latestDraft.name}`);
